name: deployment

on:
  push:
    branches:
      - main

jobs:

  dockerize:
    name: Build and Publish Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: git pull n checkout

      - name: login to docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          docker build -t ovrrtd/portfolio-web:latest .
          docker push ovrrtd/portfolio-web:latest

  deploy:
    name: Deploy to Digitalocean on main branch push
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - name: git pull n checkout
        uses: actions/checkout@v2


      - name: Deploy Container to Digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          script:
            docker pull ovrrtd/portfolio-web:latest &&
            docker stop portfolio-web || true &&
            docker rm portfolio-web || true &&
            docker run -d -it -p 3001:3001 --restart unless-stopped --name portfolio-web ovrrtd/portfolio-web:latest &&
            docker image prune -a -f